apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
  namespace: logging
  labels:
    k8s-app: fluent-bit
data:
  # Configuration files: server, input, filters and output
  # ======================================================
  fluent.conf: |
    <system>
      log_level info
    </system>
    <source>
      @type  forward
      port 24224
      bind 0.0.0.0
      #shared_key    secret
      #secure no
      #self_hostname fluentd.logger.svc
    </source>
    <match **.**>
      @type elasticsearch
      host elasticsearch.default.svc
      port 9200
      logstash_format true
    </match>
