#######################################################################
# Service to expose the Wazuh master manager API to the Kibana
# application and to other EC2 instances inside the VPC
#######################################################################

apiVersion: v1
kind: Service
metadata:
  name: wazuh  # Don't change, unless you update the Wazuh Kibana app config
  namespace: wazuh
  labels:
    app: wazuh-manager
spec:
  selector:
    app: wazuh-manager
    wazuh-manager-role: master
  ports:
    - name: wazuh-api
      port: 55000
      targetPort: 55000
