apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash.conf
  namespace: wazuh
data:
  # logstash.conf
  logstash.conf: |-
    # Wazuh - Logstash configuration file
    ## Remote Wazuh Manager - Filebeat input
    input {
        beats {
            port => 5000
            codec => "json_lines"
    #       ssl => true
    #       ssl_certificate => "/etc/logstash/logstash.crt"
    #       ssl_key => "/etc/logstash/logstash.key"
        }
    }
    filter {
        if [data][srcip] {
            mutate {
                add_field => [ "@src_ip", "%{[data][srcip]}" ]
            }
        }
        if [data][aws][sourceIPAddress] {
            mutate {
                add_field => [ "@src_ip", "%{[data][aws][sourceIPAddress]}" ]
            }
        }
    }
    filter {
        geoip {
            source => "@src_ip"
            target => "GeoLocation"
            fields => ["city_name", "continent_code", "country_code2", "country_name", "region_name", "location"]
        }
        date {
            match => ["timestamp", "ISO8601"]
            target => "@timestamp"
        }
        mutate {
            remove_field => [ "timestamp", "beat", "input_type", "tags", "count", "@version", "log", "offset", "type","@src_ip"]
        }
    }
    output {
        elasticsearch {
            hosts => ["elastic-api.elasticsearch.svc.cluster.local:9200"]
            index => "highground.wazuh.-%{+YYYY.MM.dd}"
            user => "api_user"
            password => "apiuser"
        }
    }
    
