

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wazuh-manager-master
  namespace: wazuh
  annotations:
    volume.beta.kubernetes.io/storage-class: "efs"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi

---



apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wazuh-manager-worker
  namespace: wazuh
  annotations:
    volume.beta.kubernetes.io/storage-class: "efs"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi


