apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-config
  namespace: wazuh
data:
  logstash.yml: |-
        path.config: /usr/share/logstash/config/logstash.conf
  logstash.conf: |-
        input { beats {
                port => 5044
         } }
        output {
               elasticsearch {
                  hosts => "elasticsearch.default.svc:9200"
                  manage_template => false
                  index => "highground.suricat-%{+YYYY.MM.dd}" 
                  }
              }
        
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: suricat-logstash
  namespace: wazuh
spec:
  selector:
    matchLabels:
      app: suricat-logstash
  template:
    metadata:
      labels:
        app: suricat-logstash
      name: suricat-logstash
    spec:
      volumes:
        - name: logstash-config
          configMap:
            name: logstash-config
      containers:
        - name: logstash
          image: 'docker.elastic.co/logstash/logstash:6.4.3'
          volumeMounts:
            - name: logstash-config
              mountPath: /usr/share/logstash/config/logstash.yml
              subPath: logstash.yml
            - name: logstash-config
              mountPath: /usr/share/logstash/config/logstash.conf
              subPath: logstash.conf
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: suricat-logstash
  name: suricat-logstash
spec:
  selector:
    app: suricat-logstash
  type: ClusterIP
  ports:
  - name: filebeat
    protocol: TCP
    targetPort: 5044
    port: 5044